name: Nightly build

on:
  push:
    branches:
      - master

jobs:
  build-deps:
    name: Build deps (windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          
  create-nightly-release:
    name: Create nightly release
    runs-on: windows-latest
    needs: build-deps
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create nightly release
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ secrets.OWNER }}/${{ secrets.REPOSITORY }}
          token: ${{ secrets.GALAXYSLICERNEO_ACCESS_TOKEN }}
          name: "Nightly release"
          tag_name: "nightly-${{ github.sha }}"
          prerelease: true
          draft: false
