name: Build windows deps

on:
  workflow_call:

jobs:
  build_deps:
    name: Build deps
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install dependencies
        run: |
          echo "Building slicer for windows"
          # Example: Save some windows-specific files or build artifacts
          mkdir -p build/windows
          echo "windows build artifacts" > build/windows/slicer-artifact.txt

      - name: Upload windows deps
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifacts
          path: build/windows/slicer-artifact.txt

  prepare_pkg_config:
    name: Prepare pkg-config
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  prepare_python:
    name: Prepare python
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  prepare_deps:
    name: Prepare deps
    runs-on: windows-latest
    needs:
      - build_deps
      - prepare_pkg_config
      - prepare_python
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
