name: Nightly build

on:
  schedule:
    # Every day at 00:00 UTC (UK)
    - cron: '0 23 * 1-3,11-12 *'   # From November to March (GMT — Greenwich Mean Time)
    - cron: '0 22 * 4-10 *'   # From April to October (BST — British Summer Time)
  workflow_dispatch:

jobs:
  check-recent-commit:
    name: Configure
    runs-on: ubuntu-latest
    outputs:
      is_recent: ${{ steps.state.outputs.is_recent }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List remote branches
        run: |
          git fetch --all
          git branch -r

      - name: Get Latest Commit Time
        id: commit_time
        run: |
          # Fetch the commit time of the latest commit
          LATEST_COMMIT_TIME=$(git log origin/master -1 --format="%ct")
          echo "latest_commit_time=${LATEST_COMMIT_TIME}" >> $GITHUB_ENV

      - name: Compare Commit Time with Current Time
        id: state
        run: |
          CURRENT_TIME=$(date +%s)
          COMMIT_TIME=${{ env.latest_commit_time }}
          DIFFERENCE=$((CURRENT_TIME - COMMIT_TIME))

          # Check if the commit is within 86400 seconds (1 day)
          if [ "$DIFFERENCE" -lt 86400 ]; then
            echo "✅ Commit is less than a day old."
            echo "is_recent=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Commit is older than a day."
            echo "is_recent=false" >> $GITHUB_OUTPUT
          fi
  
  # Windows nightly build      
  build-deps-windows:
    name: Deps (Windows)
    needs: check-recent-commit
    if: needs.check-recent-commit.outputs.is_recent == 'true'
    uses: fr3ak2402/BambuStudio/.github/workflows/build_deps_windows.yml@master
    secrets: inherit

  build-slicer-windows:
    name: Slicer (Windows)
    needs: build-deps-windows
    if: success()
    uses: fr3ak2402/BambuStudio/.github/workflows/build_slicer_windows.yml@master
    secrets: inherit
        
  # macOS nightly build
  build-deps-macos:
    name: Deps (macOS)
    needs: check-recent-commit
    if: needs.check-recent-commit.outputs.is_recent == 'true'
    uses: fr3ak2402/BambuStudio/.github/workflows/build_deps_macos.yml@master

  build-slicer-macos:
    name: Slicer (macOS)
    needs: build-deps-macos
    if: success()
    uses: fr3ak2402/BambuStudio/.github/workflows/build_slicer_macos.yml@master

  # Nightly release
  check-nightly-release:
    name: Check nightly release
    runs-on: ubuntu-latest
    needs:
      - build-slicer-windows
      - build-slicer-macos
    if: success() || failure()  # Run if any of the slicer jobs succeed
    outputs:
      release_exists: ${{ steps.check_release.outputs.release_exists }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if release already exists
        id: check_release
        run: |
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ vars.OWNER }}/${{ vars.REPOSITORY }}/releases/tags/V${{ vars.GSN_VERSION }}-nightly")
          
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n 1)

          if [[ "$HTTP_STATUS" == "404" ]]; then
            echo "❌ Release not found, creating a new one."
            echo "release_exists=false" >> $GITHUB_OUTPUT
          elif [[ "$HTTP_STATUS" == "200" ]]; then
            echo "✅ Release found, updating the release."
            echo "release_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Failed to check release status."
            exit 1
          fi

  create-nightly-release:
    name: Create nightly release
    runs-on: windows-latest
    needs: check-nightly-release
    if: needs.check-nightly-release.outputs.release_exists == 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check release artifact (windows)
        uses: LIT-Protocol/artifact-exists-action@v0
        id: "windows-release-state"
        with:
          name: "GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}-nightly.zip"

      - name: Download slicer (windows)
        uses: actions/download-artifact@v4
        if: ${{ steps.windows-release-state.outputs.exists == 'true' }}
        with:
          name: GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}-nightly.zip
          path: download/Slicer/windows/GalaxySlicerNeo

      - name: Check installer artifact (windows)
        uses: LIT-Protocol/artifact-exists-action@v0
        id: "windows-installer-state"
        with:
          name: "GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}_setup-nightly.exe"

      - name: Download installer (windows)
        uses: actions/download-artifact@v4
        if: ${{ steps.windows-installer-state.outputs.exists == 'true' }}
        with:
          name: GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}_setup-nightly.exe
          path: download/Slicer/windows

      - name: Prepare Release (windows)
        shell: pwsh
        if: ${{ steps.windows-release-state.outputs.exists == 'true' }}
        run: |
          $source = "download\Slicer\windows\GalaxySlicerNeo"
          $destination = "download\Slicer\windows\GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}-nightly.zip"
          Compress-Archive -Path $source -DestinationPath $destination
          Remove-Item -Path $source -Recurse -Force

      - name: Calculate slicer SHA256 hash (windows)
        id: windows-slicer-hash
        run: |
          $hash = Get-FileHash -Path download\Slicer\windows\GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}-nightly.zip -Algorithm SHA256
          Write-Output "Slicer hash: $($hash.Hash)"
          echo "windows_slicer_sha256=$($hash.Hash)" >> $GITHUB_ENV

      - name: Calculate installer SHA256 hash (windows)
        id: windows-installer-hash
        run: |
          $hash = Get-FileHash -Path download/Slicer/windows/GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}_setup-nightly.exe -Algorithm SHA256
          Write-Output "Installer hash: $($hash.Hash)"
          echo "windows_installer_sha256=$($hash.Hash)" >> $GITHUB_ENV

      - name: Generate nightly release notes
        id: nightly_release_notes
        run: |
          $content = @"
          ![GalaxySlicerNeo_nightly](https://github.com/user-attachments/assets/94257eea-6dfa-4da0-81da-76bdfc3a6766)
          -----------------------------------------
          "@

          if (${{ steps.windows-release-state.outputs.exists }} -eq 'true') {
            $content += "Package (Windows) sha256 sums:\n"
            $content += "GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}-nightly.zip: ${{ env.windows_slicer_sha256 }}\n"
          }

          if (${{ steps.windows-installer-state.outputs.exists }} -eq 'true') {
            $content += "GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}_setup-nightly.exe: ${{ env.windows_installer_sha256 }}\n"
          }

          $txtPath = "${{ github.workspace }}\release.txt"
          $content | Out-File -FilePath $txtPath -Encoding utf8

      - name: Create nightly release
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ vars.OWNER }}/${{ vars.REPOSITORY }}
          token: ${{ secrets.DEV_ACCESS_TOKEN }}
          name: "GalaxySlicerNeo V${{ vars.GSN_VERSION }} Nightly"
          tag_name: "V${{ vars.GSN_VERSION }}-nightly"
          generate_release_notes: false
          make_latest: true
          prerelease: true
          draft: false
          body_path: release.txt
          #body: |
          #  ![GalaxySlicerNeo_nightly](https://github.com/user-attachments/assets/94257eea-6dfa-4da0-81da-76bdfc3a6766)
          #  -----------------------------------------
          files: |
            download/Slicer/windows/GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}-nightly.zip
            download/Slicer/windows/GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}_setup-nightly.exe

  update-readme:
    name: Update README.md
    runs-on: ubuntu-latest
    needs: create-nightly-release
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Clone Repository
        run: |
          git clone https://github.com/${{ vars.OWNER }}/${{ vars.REPOSITORY }} repo
          cd repo
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update README.md
        run: |
          RELEASE_URL="https://github.com/${{ vars.OWNER }}/${{ vars.REPOSITORY }}/releases/tag/V${{ vars.GSN_VERSION }}-nightly"

          cd repo
          sed -i 's|https://github.com/${{ vars.OWNER }}/${{ vars.REPOSITORY }}/releases/tag/V${{ vars.NIGHTLY_VERSION }}-nightly|https://github.com/${{ vars.OWNER }}/${{ vars.REPOSITORY }}/releases/tag/V${{ vars.GSN_VERSION }}-nightly|g' README.md

      - name: Commit and push README.md
        run: |
          cd repo
          git add README.md
          git commit -m "Update README.md with new release link"
          git push https://x-access-token:${{ secrets.DEV_ACCESS_TOKEN }}@github.com/${{ vars.OWNER }}/${{ vars.REPOSITORY }}.git HEAD:main

  update-variable:
    name: Update variable
    runs-on: ubuntu-latest
    needs: update-readme
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Repository Variable
        uses: mmoyaferrer/set-github-variable@v1.0.0
        with:
          name: 'NIGHTLY_VERSION'
          value: '${{ vars.GSN_VERSION }}'
          repository: ${{ github.repository }}
          token: ${{ secrets.DEV_ACCESS_TOKEN }}

  update-nightly-release:
    name: Update nightly release
    runs-on: windows-latest
    needs: check-nightly-release
    if: needs.check-nightly-release.outputs.release_exists == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check release artifact (windows)
        uses: LIT-Protocol/artifact-exists-action@v0
        id: "windows-release-state"
        with:
          name: "GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}-nightly.zip"

      - name: Download slicer (windows)
        uses: actions/download-artifact@v4
        if: ${{ steps.windows-release-state.outputs.exists == 'true' }}
        with:
          name: GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}-nightly.zip
          path: download/Slicer/windows/content

      - name: Check installer artifact (windows)
        uses: LIT-Protocol/artifact-exists-action@v0
        id: "windows-installer-state"
        with:
          name: "GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}_setup-nightly.exe"

      - name: Download installer (windows)
        uses: actions/download-artifact@v4
        if: ${{ steps.windows-installer-state.outputs.exists == 'true' }}
        with:
          name: GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}_setup-nightly.exe
          path: download/Slicer/windows

      - name: Prepare Release (windows)
        shell: pwsh
        if: ${{ steps.windows-release-state.outputs.exists == 'true' }}
        run: |
          $source = "download\Slicer\windows\content"
          $destination = "download\Slicer\windows\GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}-nightly.zip"
          Compress-Archive -Path $source -DestinationPath $destination
          Remove-Item -Path $source -Recurse -Force

      - name: Calculate slicer SHA256 hash (windows)
        id: windows-slicer-hash
        run: |
          $hash = Get-FileHash -Path download\Slicer\windows\GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}-nightly.zip -Algorithm SHA256
          Write-Output "Slicer hash: $($hash.Hash)"
          echo "windows_slicer_sha256=$($hash.Hash)" >> $GITHUB_ENV

      - name: Calculate installer SHA256 hash (windows)
        id: windows-installer-hash
        run: |
          $hash = Get-FileHash -Path download/Slicer/windows/GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}_setup-nightly.exe -Algorithm SHA256
          Write-Output "Installer hash: $($hash.Hash)"
          echo "windows_installer_sha256=$($hash.Hash)" >> $GITHUB_ENV

      - name: Generate nightly release notes
        id: nightly_release_notes
        run: |
          $windows_release_state = ${{ steps.windows-release-state.outputs.exists }}
          $windows_installer_state = ${{ steps.windows-installer-state.outputs.exists }}

          $content = @"
          ![GalaxySlicerNeo_nightly](https://github.com/user-attachments/assets/94257eea-6dfa-4da0-81da-76bdfc3a6766)
          -----------------------------------------
          "@

          if ($windows_release_state -eq 'true') {
            $content += "Package (Windows) sha256 sums:\n"
            $content += "GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}-nightly.zip: ${{ env.windows_slicer_sha256 }}\n"
          }

          if ($windows_installer_state -eq 'true') {
            $content += "GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}_setup-nightly.exe: ${{ env.windows_installer_sha256 }}\n"
          }

          $mdPath = "${{ github.workspace }}\release.md"
          $content | Out-File -FilePath $mdPath -Encoding utf8
      
      - name: Update nightly release
        uses: ncipollo/release-action@v1.14.0
        with:
          owner: ${{ vars.OWNER }}
          repo: ${{ vars.REPOSITORY }}
          token: ${{ secrets.DEV_ACCESS_TOKEN }}
          name: "GalaxySlicerNeo V${{ vars.GSN_VERSION }} Nightly"
          tag: "V${{ vars.GSN_VERSION }}-nightly"
          allowUpdates: true
          generateReleaseNotes: false
          makeLatest: true
          prerelease: true
          draft: false
          replacesArtifacts: true
          bodyFile: "release.md"
          artifacts: "download/Slicer/windows/GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}-nightly.zip, download/Slicer/windows/GalaxySlicerNeo_win_x64_v${{ vars.GSN_VERSION }}_setup-nightly.exe"