name: Build Nightly

on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: windows-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Create nightly release
        id: create_release
        uses: viperproject/create-nightly-release@v1
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GALAXYSLICERNEO_ACCESS_TOKEN }}
        with:
          tag_name: 'nightly'
          release_name: Nightly Release nightly
          body: Body for the release
          keep_num: 0
          keep_tags: false
