name: Nightly build

on:
  push:
    branches:
      - master

jobs:
  build-deps-windows:
    name: Build deps (windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."

  build-slicer-windows:
    name: Build slicer (windows)
    runs-on: windows-latest
    needs: build-deps-windows
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  build-deps-macos:
    name: Build deps (macos)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."

  build-slicer-macos:
    name: Build slicer (macos)
    runs-on: macos-latest
    needs: build-deps-macos
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build slicer on macOS
        run: |
          echo "Building slicer for macOS"
          # Example: Save some macOS-specific files or build artifacts
          mkdir -p build/macOS
          echo "macOS build artifacts" > build/macOS/slicer-artifact.txt

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macOS-build-artifacts
          path: build/macOS/slicer-artifact.txt

  create-nightly-release:
    name: Create nightly release
    runs-on: windows-latest
    needs: 
      - build-slicer-windows
      - build-slicer-macos
    if: success('build-slicer-windows') || success('build-slicer-macos')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create nightly release
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ secrets.OWNER }}/${{ secrets.REPOSITORY }}
          token: ${{ secrets.GALAXYSLICERNEO_ACCESS_TOKEN }}
          name: "Nightly release"
          tag_name: "nightly"
          prerelease: true
          draft: false
