name: Nightly build

on:
  push:
    branches:
      - master

jobs:
  check-commit:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'push' }}
        run: test -z $(git rev-list  --after="24 hours" ${{ github.sha }}) && echo "should_run=false" >> $GITHUB_OUTPUT
          
  # Windows nightly build      
  build-deps-windows:
    name: Deps (Windows)
    needs: check-commit
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: fr3ak2402/BambuStudio/.github/workflows/build_deps_windows.yml@master

  build-slicer-windows:
    name: Slicer (Windows)
    needs: build-deps-windows
    if: success()
    uses: fr3ak2402/BambuStudio/.github/workflows/build_slicer_windows.yml@master
        
  # macOS nightly build
  build-deps-macos:
    name: Deps (macOS)
    needs: check-commit
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  build-slicer-macos:
    name: Slicer (macOS)
    runs-on: macos-latest
    needs: build-deps-macos
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  create-nightly-release:
    name: Create nightly release
    runs-on: windows-latest
    needs:
      - build-slicer-windows
      - build-slicer-macos
    if: success() || failure()  # Run if any of the slicer jobs succeed
    steps:
      - name: Checkout
        uses: actions/checkout@v4

     # - name: Create nightly release
     #   uses: softprops/action-gh-release@v2
     #   with:
     #     repository: ${{ vars.OWNER }}/${{ vars.REPOSITORY }}
     #     token: ${{ secrets.GALAXYSLICERNEO_ACCESS_TOKEN }}
     #     name: "GalaxySlicerNeo V${{ vars.GSN_VERSION }} Nightly build"
     #     tag_name: "V${{ vars.GSN_VERSION }}-nightly"
     #     prerelease: true
     #     draft: false
