name: Nightly build

on:
  push:
    branches:
      - master

jobs:
  # Windows nightly build
  setup-environment-windows:
    name: Setup environment (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  build-deps-windows:
    name: Build deps (Windows)
    runs-on: windows-latest
    needs: setup-environment-windows
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "Installing dependencies on Windows"

  build-slicer-windows:
    name: Build slicer (Windows)
    runs-on: windows-latest
    needs: build-deps-windows
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  # macOS nightly build
  setup-environment-macos:
    name: Setup environment (macOS)
    runs-on: macos-latest  # Fixed from 'windows-latest' to 'macos-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  build-deps-macos:
    name: Build deps (macOS)
    runs-on: macos-latest
    needs: setup-environment-macos
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "Installing dependencies on macOS"

  build-slicer-macos:
    name: Build slicer (macOS)
    runs-on: macos-latest
    needs: build-deps-macos
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build slicer on macOS
        run: |
          echo "Building slicer for macOS"
          # Example: Save macOS-specific files or build artifacts
          mkdir -p build/macOS
          echo "macOS build artifacts" > build/macOS/slicer-artifact.txt

  upload-deps-macos:
    name: Upload macOS build artifacts
    runs-on: macos-latest
    needs: build-slicer-macos
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload macOS build artifact
        uses: actions/upload-artifact@v3
        with:
          name: macOS-build-artifacts
          path: build/macOS/slicer-artifact.txt

  create-nightly-release:
    name: Create nightly release
    runs-on: windows-latest
    needs:
      - build-slicer-windows
      - build-slicer-macos
    if: success() || failure()  # Will run if either of the build jobs succeed
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download macOS build artifact
        uses: actions/download-artifact@v3
        with:
          name: macOS-build-artifacts
          path: build/macOS

      - name: Create nightly release
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ secrets.OWNER }}/${{ secrets.REPOSITORY }}
          token: ${{ secrets.GALAXYSLICERNEO_ACCESS_TOKEN }}
          name: "Nightly release"
          tag_name: "nightly-${{ github.sha }}"
          prerelease: true
          draft: false

      - name: Use macOS artifact in release process
        run: |
          echo "Using macOS artifact in release process"
          cat build/macOS/slicer-artifact.txt
          # You can now use the artifact in the release process (for example, attach it or include it in the release notes)
