name: Prepare pkg-config (Windows)

on:
  workflow_call:

jobs:
  prepare:
    name: Prepare pkg-config
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        run: |
            mkdir ${{ github.workspace }}/download
            echo Start downloading pkg-config files...
            powershell -Command "Invoke-WebRequest https://github.com/fr3ak2402/GalaxySlicer_deps/releases/download/September_23/pkg-config-lite-0.28.1.zip -OutFile ${{ github.workspace }}/download/pkg-config.zip"

      - name: Unzip
        run: |
            mkdir ${{ github.workspace }}/download/pkg-config
            powershell -command "Expand-Archive -Path '${{ github.workspace }}/download/pkg-config.zip' -DestinationPath ${{ github.workspace }}/download/pkg-config'"

      - name: Cache pkg-config
        uses: actions/cache/save@v4
        id: cache-pkgconfig
        with:
          path: ${{ github.workspace }}/download/pkg-config.zip
          key: ${{ github.sha }}-pkgconfig
