name: Prepare python (Windows)

on:
  workflow_call:

jobs:
  prepare:
    name: Prepare python
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        run: |
            mkdir ${{ github.workspace }}/download
            echo "Downloading Python ${{ secrets.TEST }}..."
            powershell -Command "Invoke-WebRequest https://www.python.org/ftp/python/${{ secrets.TEST }}/python-${{ secrets.TEST }}-embed-amd64.zip -OutFile '${{ github.workspace }}\download\python.zip'"

      - name: Unzip
        run: |
            mkdir ${{ github.workspace }}/download/python
            powershell -command "Expand-Archive -Path '${{ github.workspace }}/download/python.zip' -DestinationPath '${{ github.workspace }}/download/python'"
            
      - name: Cache python
        uses: actions/cache/save@v4
        id: cache-python
        with:
          path: ${{ github.workspace }}/download/python
          key: ${{ github.sha }}-python
          
