name: Prepare python (Windows)

on:
  workflow_call:

jobs:
  prepare:
    name: Prepare python
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        run: |
            mkdir ${{ github.workspace }}/download
            echo Downloading Python...
            powershell -Command "Invoke-WebRequest https://www.python.org/ftp/python/3.13.1/python-3.13.1-embed-amd64.zip -OutFile ${{ github.workspace }}/download/python.zip"

      - name: Cache python
        uses: actions/cache/save@v4
        id: cache-python
        with:
          path: ${{ github.workspace }}/download/python.zip
          key: ${{ github.sha }}-python
