name: Prepare python (Windows)

on:
  workflow_call:

jobs:
  check:
    name: Check latest python version
    runs-on: ubuntu-latest
    outputs:
      is_outdated: ${{ steps.compare_python.outputs.is_outdated }}
      latest_version: ${{ steps.compare_python.outputs.latest_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest stable Python version
        id: get_version
        run: |
          # Fetch the JSON file with the version information
          response=$(curl -s https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json)
          
          # Extract the latest stable version
          python_version=$(echo "$response" | jq -r '.[] | select(.stable == true) | .version' | head -n 1)
          
          echo "Latest stable Python version: $python_version"

          # Set the extracted version as an environment variable
          echo "latest_release=$python_version" >> $GITHUB_ENV

      - name: Compare Python versions
        id: compare_python
        run: |
          cache_python_version="${{ vars.PYTHON_VERSION }}"
          echo "Cache Python release is: $cache_python_version"

          latest_release="${{ env.latest_release }}"

          if [ "$latest_release" == "$cache_python_version" ]; then
            echo "✅ The Python version is up to date!"

            echo "is_outdated=false" >> $GITHUB_OUTPUT
            echo "latest_version=$latest_release" >> $GITHUB_OUTPUT
          else
            echo "❌ The Python version ($cache_python_version) is outdated!"
            
            echo "is_outdated=true" >> $GITHUB_OUTPUT
            echo "latest_version=$latest_release" >> $GITHUB_OUTPUT
          fi

  update:
    name: Update Repository Variable
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.is_outdated == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #- name: Update Repository Variable
      #  run: |
      #    curl -L \
      #      -X PATCH \
      #      -H "Accept: application/vnd.github+json" \
      #      -H "Authorization: Bearer ${{ secrets.GALAXYSLICER_ACCESS_TOKEN }}" \
      #      -H "X-GitHub-Api-Version: 2022-11-28" \
      #      https://api.github.com/repos/${{ github.repository }}/actions/variables/PYTHON_VERSION \
      #      -d '{"name":"PYTHON_VERSION", "value": "${{ needs.check.outputs.latest_version }}"}' 

  prepare:
    name: Prepare python
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check cache
        id: check-cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/download/python
          key: python-${{ vars.PYTHON_VERSION }}

      - name: Download
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: |
            mkdir ${{ github.workspace }}/download
            echo "Downloading Python ${{ vars.PYTHON_VERSION }}..."
            powershell -Command "Invoke-WebRequest https://www.python.org/ftp/python/${{ vars.PYTHON_VERSION }}/python-${{ vars.PYTHON_VERSION }}-embed-amd64.zip -OutFile '${{ github.workspace }}\download\python.zip'"

      - name: Unzip
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: |
            mkdir ${{ github.workspace }}/download/python
            powershell -command "Expand-Archive -Path '${{ github.workspace }}/download/python.zip' -DestinationPath '${{ github.workspace }}/download/python'"
            
      - name: Cache python
        if: steps.check-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        id: cache-python
        with:
          path: ${{ github.workspace }}/download/python
          key: python-${{ vars.PYTHON_VERSION }}
          
