name: Prepare python (Windows)

on:
  workflow_call:

jobs:
  prepare:
    name: Prepare python
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch python version
        id: fetch_variable
        run: |
          # GitHub API Request to fetch the variable
          $response = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/actions/variables/PYTHON_VERSION" `
                                        -Headers @{ 
                                            "Accept" = "application/vnd.github+json"
                                            "Authorization" = "Bearer ${{ secrets.DEV_ACCESS_TOKEN }}"
                                            "X-GitHub-Api-Version" = "2022-11-28"
                                        }
          
          $value = $response.value
          echo "PYTHON_VERSION=$value" >> $env:GITHUB_ENV

      - name: Check cache
        id: check-cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/download/python
          key: python-${{ env.PYTHON_VERSION }}

      - name: Download
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: |
            mkdir ${{ github.workspace }}/download
            echo "Downloading Python ${{ env.PYTHON_VERSION }}..."
            powershell -Command "Invoke-WebRequest https://www.python.org/ftp/python/${{ env.PYTHON_VERSION }}/python-${{ env.PYTHON_VERSION }}-embed-amd64.zip -OutFile '${{ github.workspace }}\download\python.zip'"

      - name: Unzip
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: |
            mkdir ${{ github.workspace }}/download/python
            powershell -command "Expand-Archive -Path '${{ github.workspace }}/download/python.zip' -DestinationPath '${{ github.workspace }}/download/python'"
            
      - name: Cache python
        if: steps.check-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        id: cache-python
        with:
          path: ${{ github.workspace }}/download/python
          key: python-${{ env.PYTHON_VERSION }}
          
